server:
  servlet:
    contextPath: /map-exercise
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:DEV100;MODE=MySQL;INIT=RUNSCRIPT FROM 'classpath:init.sql';DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;
    username: dbuser
    password: 1234
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: org.h2.Driver
    initialization-mode: always
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: DEV100
  h2:
    console:
      enabled: true
      path: /h2-console